project:
  type: website

website:
  title: "Allen Sunny"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Coursework"
        href: coursework.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



